### PR TITLE
Update sage.yml

### PR DESCRIPTION
**Pull request by MWDelaney**
Update example to follow [existing example](https://github.com/roots/trellis/blob/master/deploy-hooks/build-before.yml) in Trellis config

### CODE REVIEW

**Comment by swalkinshaw** [comment]
🤔 this is inconsistent with https://github.com/roots/setup-trellis-cli/blob/main/examples/multi-repo.yml now

**Comment by MWDelaney** [comment]
Super good point. Happy to add simple comments to the top of the other two examples!

**Comment by swalkinshaw** [comment]
Yeah adding the comment header + calling out what needs to be replaced would be helpful on eall 3

**Comment by swalkinshaw** [comment]
Thanks 🎉

**Pull request merged**
